remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "adiomusika"
description: "A free offline audio and music player for Android focused on the joy of listening to sound!"
author:
  name: "Jamond Alexandre"

# Do not change the following line.
  copyright: true
